name: CI/CD Shop24 deploy.yml
on:
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            server-side/package-lock.json
            client-side/package-lock.json

      # ---------- SERVER ----------
      - name: Install server deps
        working-directory: server-side
        run: npm ci

      - name: Prisma generate (server)
        working-directory: server-side
        run: npx prisma generate

      - name: Test server
        working-directory: server-side
        run: npm run test -- --runInBand

      - name: Build server
        working-directory: server-side
        run: npm run build

      # ---------- CLIENT ----------
      - name: Install client deps (with optional)
        working-directory: client-side
        run: npm ci --include=optional

      - name: Build client
        working-directory: client-side
        run: npm run build
        env:
          SERVER_URL_INTERNAL: http://server:5000


      # ---------- DOCKER (validate dockerfiles) ----------
      - name: Build docker images
        run: docker compose build

      - name: Start stack
        run: docker compose up -d

      - name: Wait
        run: sleep 10

      - name: Check server port
        run: curl -f http://localhost:5000 || (docker compose logs && exit 1)

      - name: Stop stack
        if: always()
        run: docker compose down -v